# SPDX-License-Identifier: MIT
# Licensed under MIT
"""Qarar sovereign cybersecurity analysis agent.

The module follows a hexagonal boundary: ``QararSecurityAgent`` owns incident
analysis orchestration while the injected ``SecurityInferencePort`` owns model
transport. No network or external runtime is imported here.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Mapping, Protocol, Sequence


SECRET_MARKER_PATTERN = re.compile(
    r"(?i)(secret|api[_-]?key|token|bearer|akia[0-9a-z]*|sk-[0-9a-z_-]+|ghp_[0-9a-z_]+|github_pat_[0-9a-z_]+)"
)
DESTRUCTIVE_ACTION_PATTERN = re.compile(
    r"(?i)\b(delete|destroy|drop|wipe|revoke|disable|quarantine|isolate|terminate|block)\b"
)


class SecurityInferencePort(Protocol):
    """Port implemented by protected local or backend-only inference adapters."""

    async def generate(self, payload: Mapping[str, Any]) -> str:
        """Generate a security analysis response.

        Args:
            payload: Sanitized prompt and deterministic generation controls.

        Returns:
            Model-generated analysis text.
        """


@dataclass(frozen=True)
class SecretScanAssessment:
    """Structured assessment for repository secret scan output.

    Args:
        has_findings: Whether the scan text contains likely secret indicators.
        requires_escalation: Whether a human security review is required before
            continuing.
        evidence_markers: Stable non-secret marker names that triggered review.
    """

    has_findings: bool
    requires_escalation: bool
    evidence_markers: tuple[str, ...]


class QararSecurityAgent:
    """Sovereign cybersecurity operations and compliance analysis agent.

    The agent is transport-agnostic and uses dependency injection for inference.
    It prepares concise evidence-backed prompts, blocks obvious secret leakage,
    and forces destructive response recommendations into draft-and-escalate mode.

    Args:
        llm_inference_port: Adapter that satisfies ``SecurityInferencePort``.
        max_context_chars: Maximum context characters retained in the prompt.
        max_log_chars: Maximum incident-log characters retained in the prompt.
    """

    SYSTEM_PROMPT = """
You are "Qarar-Sec", a Sovereign Cybersecurity Operations and Compliance Agent.
Analyze security events, propose SOAR actions, and provide concise,
evidence-backed mitigation steps.
Map vulnerabilities to NCA ECC-2:2024 control families only as draft analysis,
not as a compliance certification.
Preserve PDPL data-minimization principles and do not echo secrets or personal data.
Always recommend "Draft-and-Escalate" for destructive actions.
""".strip()

    def __init__(
        self,
        llm_inference_port: SecurityInferencePort,
        *,
        max_context_chars: int = 12_000,
        max_log_chars: int = 16_000,
    ) -> None:
        self.llm = llm_inference_port
        self.max_context_chars = max_context_chars
        self.max_log_chars = max_log_chars

    async def analyze_incident(
        self,
        incident_logs: str,
        context_files: Sequence[str] | None = None,
    ) -> str:
        """Analyze security logs and request a draft mitigation plan.

        Args:
            incident_logs: EDR, SIEM, WAF, or audit log text to analyze.
            context_files: Optional evidence snippets such as firewall policy or
                control guidance excerpts. Values are treated as untrusted input.

        Returns:
            Security analysis generated by the injected inference adapter.

        Raises:
            ValueError: If logs are empty or unsafe secret-like markers are
                present in logs or context evidence.
        """

        sanitized_logs = self._sanitize_input(
            incident_logs, field_name="incident_logs", max_chars=self.max_log_chars
        )
        context = self._build_context(context_files or ())
        prompt = self._build_prompt(sanitized_logs, context)
        payload: dict[str, Any] = {
            "prompt": prompt,
            "temperature": 0.1,
            "max_tokens": 2048,
            "safety_mode": "draft_and_escalate",
        }
        response = await self.llm.generate(payload)
        return self._enforce_draft_escalation(response)

    def parse_secrets_scan(self, scan_results: str) -> SecretScanAssessment:
        """Assess secret-scan output without returning secret values.

        Args:
            scan_results: Raw text emitted by tools such as gitleaks or
                trufflehog. The text is treated as sensitive and never echoed.

        Returns:
            Structured non-secret assessment with marker names only.
        """

        if not scan_results.strip():
            return SecretScanAssessment(
                has_findings=False,
                requires_escalation=False,
                evidence_markers=(),
            )

        marker_matches = {
            self._normalize_secret_marker(match.group(1))
            for match in SECRET_MARKER_PATTERN.finditer(scan_results)
        }
        evidence_markers = tuple(sorted(marker_matches))
        has_findings = bool(evidence_markers)
        return SecretScanAssessment(
            has_findings=has_findings,
            requires_escalation=has_findings,
            evidence_markers=evidence_markers,
        )

    def _normalize_secret_marker(self, marker: str) -> str:
        """Return a non-secret marker class for a secret scan match."""

        normalized = marker.lower().replace("-", "_")
        if normalized.startswith("github_pat_"):
            return "github_pat"
        if normalized.startswith("ghp_"):
            return "ghp"
        if normalized.startswith("sk_"):
            return "sk"
        if normalized.startswith("akia"):
            return "akia"
        return normalized

    def _build_context(self, context_files: Sequence[str]) -> str:
        """Build sanitized evidence context from optional file snippets."""

        sanitized_files = [
            self._sanitize_input(
                content,
                field_name="context_files",
                max_chars=self.max_context_chars,
                allow_empty=True,
            )
            for content in context_files
        ]
        if not sanitized_files:
            return "No additional context supplied."
        return "\n".join(
            f"--- Evidence File {index} ---\n{content}"
            for index, content in enumerate(sanitized_files, start=1)
        )

    def _build_prompt(self, incident_logs: str, context: str) -> str:
        """Build the final model prompt for the injected adapter."""

        return (
            f"{self.SYSTEM_PROMPT}\n\n"
            "Please analyze the following security incident logs and provide:\n"
            "1. Incident summary with evidence references.\n"
            "2. Severity and confidence.\n"
            "3. SOAR actions, with destructive actions marked Draft-and-Escalate.\n"
            "4. Draft ECC-2:2024 control-family mapping without compliance claims.\n"
            "5. PDPL data-minimization and containment notes.\n\n"
            f"[Context/Evidence]:\n{context}\n\n"
            f"[Incident Logs]:\n{incident_logs}"
        )

    def _sanitize_input(
        self,
        value: str,
        *,
        field_name: str,
        max_chars: int,
        allow_empty: bool = False,
    ) -> str:
        """Validate prompt input and block obvious secret leakage."""

        normalized = value.strip()
        if not normalized and not allow_empty:
            raise ValueError(f"{field_name} must not be empty")
        if SECRET_MARKER_PATTERN.search(normalized):
            raise ValueError(f"{field_name} contains secret-like markers")
        if len(normalized) > max_chars:
            return normalized[:max_chars] + "\n[TRUNCATED_BY_QARAR_SECURITY_AGENT]"
        return normalized

    def _enforce_draft_escalation(self, response: str) -> str:
        """Append a safety reminder when destructive verbs appear in output."""

        if not DESTRUCTIVE_ACTION_PATTERN.search(response):
            return response
        if "Draft-and-Escalate" in response:
            return response
        return f"{response}\n\nSafety: Draft-and-Escalate required before destructive action."
